#!/bin/sh
rm -f aper.fits
rm -f default.param
rm -f  ell.cl
rm -f  field.cat
rm -f  sex.xml
rm -f  *.png
rm -f  *.pyc
rm -f  default.psf
rm -f  ellipse.txt
rm -f  galaxy_clean.fits
rm -f  *.par
rm -f  badpix.txt
rm -f  default.conv
rm -f  default.sex
rm -f  galaxy.fits
rm -f  segm.fits
rm -f cuts.cl
rm -f profileima.fits
rm -f profilepsf.fits
rm -f deconv.cl
rm -f imadeconv.fits
rm -f imadeconv.hhd
rm -f madeconv.hhh
rm -f profileima.hhd
rm -f profileima.hhh
rm -f profilepsf.hhd
rm -f profilepsf.hhh
rm -f imadeconv.hhh
rm -f *.hhh
rm -f *.hhd
rm -f modelPSF.txt
rm -f psf_model.fits
rm -f ximag.*
rm -f subcomps.fits
rm -f galfit.*
rm -f fit.log
rm -f galfit_out.fits
rm -f *.imh
rm -f bulge.fits
rm -f disk.fits
rm -f resid.fits
rm -f model.fits
rm -f profiledisk.fits
rm -f profilemodel.fits
rm -f profilebulge.fits
rm -f profileresid.fits
rm -f field.fits
rm -f fon.fits
rm -f objects.fits
rm -f bad_pix_stars.txt
rm -f modelIN.txt
rm -f default.nnw
rm -f psf_models.fits
rm -f field1.fits
rm -f field_clean.fits
rm -f psf.cl
rm -f psf.fits
rm -f input.txt
rm -f second.sex
rm -f out.pdf
rm -f output.txt
rm -f profiles.cl
rm -f backgr1.fits
rm -f *.imh
rm -f *.pix
rm -f ..bulge.imh
rm -f ..disk.imh
rm -f ..model.imh
rm -f ..resid.imh
rm -f models.txt
rm -f out.log
rm -f ini.txt
rm -f constr.txt
rm -f diskRES.fits
rm -f disk_fit.fits
rm -f bulgeRES.fits
rm -f bulge_fit.fits
rm -f zima.fits
rm -f zimamodel.fits
rm -f zmodel.fits
rm -f field2.fits
rm -f field3.fits
rm -f resid_wt_cont.fits
rm -f galaxy_wt_cont.fits
rm -f out.fits
